# fly.toml app configuration file generated for hello-fly-private-dddssa on 2024-11-28T11:31:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-fly-private-dddssa'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
