# fly.toml app configuration file generated for app-frosty-shadow-6860 on 2024-09-27T11:28:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-frosty-shadow-6860'
primary_region = 'iad'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
